/**
 * Client-Side Google Workspace API Integration Service
 * Calls 1P Google Workspace REST APIs using the authenticated Bearer token.
 * Scope Minimization & User Confirmation enforced.
 */

export interface GoogleDriveFile {
  id: string;
  name: string;
  mimeType: string;
  webViewLink?: string;
  createdTime?: string;
}

export interface GoogleDocResult {
  documentId: string;
  title: string;
  url: string;
}

export interface GoogleTaskResult {
  id: string;
  title: string;
  notes?: string;
  due?: string;
  status: string;
}

export interface GoogleFormResult {
  formId: string;
  responderUri: string;
  editUrl: string;
  title: string;
}

export interface GoogleMeetResult {
  meetingUri: string;
  meetingCode: string;
}

/**
 * Upload a text or markdown legal file to Google Drive
 */
export async function uploadToGoogleDrive(
  accessToken: string,
  filename: string,
  content: string,
  mimeType = 'text/plain'
): Promise<GoogleDriveFile> {
  const metadata = {
    name: filename,
    mimeType: mimeType,
    description: 'Generated by PA Legal Reference & Practice Portal'
  };

  const boundary = '-------314159265358979323846';
  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelimiter = `\r\n--${boundary}--`;

  const multipartRequestBody =
    delimiter +
    'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
    JSON.stringify(metadata) +
    delimiter +
    `Content-Type: ${mimeType}\r\n\r\n` +
    content +
    closeDelimiter;

  const response = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,webViewLink,createdTime',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': `multipart/related; boundary=${boundary}`
      },
      body: multipartRequestBody
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Google Drive API error (${response.status}): ${errorText}`);
  }

  return response.json();
}

/**
 * List files created in Google Drive by the user
 */
export async function listGoogleDriveFiles(accessToken: string): Promise<GoogleDriveFile[]> {
  const query = encodeURIComponent("trashed = false");
  const response = await fetch(
    `https://www.googleapis.com/drive/v3/files?q=${query}&fields=files(id,name,mimeType,webViewLink,createdTime)&orderBy=createdTime desc&pageSize=20`,
    {
      headers: {
        Authorization: `Bearer ${accessToken}`
      }
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Google Drive list files error (${response.status}): ${errorText}`);
  }

  const data = await response.json();
  return data.files || [];
}

/**
 * Create a formatted Google Document with legal pleading or analysis content
 */
export async function createGoogleDoc(
  accessToken: string,
  title: string,
  bodyText: string
): Promise<GoogleDocResult> {
  // 1. Create blank doc
  const createRes = await fetch('https://docs.googleapis.com/v1/documents', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ title })
  });

  if (!createRes.ok) {
    const errText = await createRes.text();
    throw new Error(`Google Docs creation error (${createRes.status}): ${errText}`);
  }

  const docData = await createRes.json();
  const documentId = docData.documentId;

  // 2. Insert formatted text content
  if (bodyText.trim()) {
    const updateRes = await fetch(
      `https://docs.googleapis.com/v1/documents/${documentId}:batchUpdate`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          requests: [
            {
              insertText: {
                location: { index: 1 },
                text: `${bodyText}\n\n[Prepared via Pennsylvania Legal Practice Portal - Unified Judicial System]`
              }
            }
          ]
        })
      }
    );

    if (!updateRes.ok) {
      console.warn('Doc created, but failed to insert text content:', await updateRes.text());
    }
  }

  return {
    documentId,
    title,
    url: `https://docs.google.com/document/d/${documentId}/edit`
  };
}

/**
 * Create a statutory legal task in Google Tasks
 */
export async function createGoogleTask(
  accessToken: string,
  title: string,
  notes: string,
  dueDate?: string // YYYY-MM-DD
): Promise<GoogleTaskResult> {
  const taskPayload: any = {
    title,
    notes
  };

  if (dueDate) {
    // RFC 3339 format for Google Tasks
    taskPayload.due = new Date(dueDate).toISOString();
  }

  const response = await fetch('https://tasks.googleapis.com/tasks/v1/lists/@default/tasks', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(taskPayload)
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Google Tasks error (${response.status}): ${errorText}`);
  }

  return response.json();
}

/**
 * List active tasks from Google Tasks
 */
export async function listGoogleTasks(accessToken: string): Promise<GoogleTaskResult[]> {
  const response = await fetch(
    'https://tasks.googleapis.com/tasks/v1/lists/@default/tasks?maxResults=20&showCompleted=false',
    {
      headers: {
        Authorization: `Bearer ${accessToken}`
      }
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Google Tasks list error (${response.status}): ${errorText}`);
  }

  const data = await response.json();
  return data.items || [];
}

/**
 * Send a message or update to a Google Chat space
 */
export async function sendGoogleChatMessage(
  accessToken: string,
  spaceName: string,
  text: string
): Promise<{ name: string; text: string }> {
  // If no spaceName is provided, list user spaces
  let targetSpace = spaceName;
  if (!targetSpace) {
    const spacesRes = await fetch('https://chat.googleapis.com/v1/spaces?pageSize=5', {
      headers: { Authorization: `Bearer ${accessToken}` }
    });
    if (spacesRes.ok) {
      const spacesData = await spacesRes.json();
      if (spacesData.spaces && spacesData.spaces.length > 0) {
        targetSpace = spacesData.spaces[0].name;
      }
    }
  }

  if (!targetSpace) {
    throw new Error('No Google Chat space found. Please create or specify a Chat Space name.');
  }

  const response = await fetch(`https://chat.googleapis.com/v1/${targetSpace}/messages`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ text })
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Google Chat API error (${response.status}): ${errText}`);
  }

  return response.json();
}

/**
 * Create a new Client Intake Questionnaire in Google Forms
 */
export async function createGoogleForm(
  accessToken: string,
  title: string,
  description: string,
  questions: { title: string; required?: boolean }[]
): Promise<GoogleFormResult> {
  // 1. Create Form
  const createRes = await fetch('https://forms.googleapis.com/v1/forms', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      info: {
        title,
        documentTitle: title
      }
    })
  });

  if (!createRes.ok) {
    const errorText = await createRes.text();
    throw new Error(`Google Forms error (${createRes.status}): ${errorText}`);
  }

  const formData = await createRes.json();
  const formId = formData.formId;

  // 2. Add question items via batchUpdate
  if (questions.length > 0) {
    const requests = questions.map((q, idx) => ({
      createItem: {
        item: {
          title: q.title,
          questionItem: {
            question: {
              required: q.required ?? true,
              textQuestion: {
                paragraph: true
              }
            }
          }
        },
        location: { index: idx }
      }
    }));

    await fetch(`https://forms.googleapis.com/v1/forms/${formId}:batchUpdate`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${accessToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ requests })
    });
  }

  return {
    formId,
    responderUri: formData.responderUri || `https://docs.google.com/forms/d/${formId}/viewform`,
    editUrl: `https://docs.google.com/forms/d/${formId}/edit`,
    title
  };
}

/**
 * Schedule a client consultation or conciliation preparation space in Google Meet
 */
export async function createGoogleMeetSpace(
  accessToken: string
): Promise<GoogleMeetResult> {
  const response = await fetch('https://meet.googleapis.com/v1/spaces', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      config: {
        accessType: 'OPEN'
      }
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Google Meet API error (${response.status}): ${errorText}`);
  }

  const data = await response.json();
  return {
    meetingUri: data.meetingUri,
    meetingCode: data.meetingCode || data.meetingUri?.split('/').pop() || 'meet-call'
  };
}
